import { useEffect, useState, useRef } from 'react';
import { EditorContent, useEditor } from '@tiptap/react';
import type { Editor } from '@tiptap/core';
import StarterKit from '@tiptap/starter-kit';
import { Bold, Italic, List, ListOrdered, Redo2, Undo2 } from 'lucide-react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { FileInput } from '@/components/ui/file-input';
import { getObjectStorageUrl, StorageImage } from '@/components/ui/storage-image';
import type { DocumentTemplate } from '@/@types/document-template.types';
import { documentTemplateSchema, type DocumentTemplateFormValues } from '@/scheme/document-template.schema';

const dummyRows = [
  ['1', 'Honda Vario 160', 'Hitam', 'MH1PC...', 'JFX1...', 'Rp 28.500.000'],
  ['2', 'Honda PCX 160', 'Putih', 'MH1KF...', 'K1Z1...', 'Rp 32.000.000'],
];

const translations = {
  id: {
    nameLabel: 'Nama Template',
    languageLabel: 'Bahasa',
    subjectFieldLabel: 'Subject',
    headerInformationLabel: 'Konten Header',
    headerInformationHint: 'Pesan yang ditampilkan di bawah subject.',
    tableColorLabel: 'Warna Header Tabel',
    signatureLabel: 'Tanda Tangan',
    signatureHint: 'Upload gambar tanda tangan yang akan ditampilkan di atas nama penandatangan.',
    signerLabel: 'Penandatangan',
    documentLabel: 'Desain Dokumen',
    invoiceNumber: 'Nomor Invoice',
    subjectLabel: 'Perihal',
    toLabel: 'Kepada',
    dateLabel: 'Yogyakarta, 23 Agustus 2026',
    salutation: 'Dengan hormat,',
    intro: 'Berikut adalah rincian transaksi yang dihasilkan oleh sistem:',
    tableHeaders: ['NO', 'TIPE UNIT', 'WARNA', 'NO RANGKA', 'NO MESIN', 'HARGA'],
    total: 'TOTAL',
    paymentInfo: 'Informasi Pembayaran',
    closing: 'Hormat kami,',
    defaultSubject: 'Invoice Pembayaran Motor',
    defaultFooterInfo: 'Mohon pembayaran dapat dilakukan ke :\nNama : PT. WAJIRA JAGRATARA MORINDO\nNo Rekening BCA : 456-581-1313\nNPWP : 65.546.691.0-542.000',
    cancel: 'Batal',
    save: 'Simpan',
    saving: 'Menyimpan...',
    fallbackSubject: 'DOKUMEN TEMPLATE',
    paymentPlaceholder: 'Informasi pembayaran',
  },
  en: {
    nameLabel: 'Template Name',
    languageLabel: 'Language',
    subjectFieldLabel: 'Subject',
    headerInformationLabel: 'Header Content',
    headerInformationHint: 'Message displayed below the subject.',
    tableColorLabel: 'Table Header Color',
    signatureLabel: 'Signature',
    signatureHint: 'Upload a signature image to display above the signer name.',
    signerLabel: 'Signer',
    documentLabel: 'Document Design',
    invoiceNumber: 'Invoice Number',
    subjectLabel: 'Subject',
    toLabel: 'To',
    dateLabel: 'Yogyakarta, August 23, 2026',
    salutation: 'Dear Sir/Madam,',
    intro: 'Here are the transaction details generated by the system:',
    tableHeaders: ['NO', 'UNIT TYPE', 'COLOR', 'FRAME NO', 'ENGINE NO', 'PRICE'],
    total: 'TOTAL',
    paymentInfo: 'Payment Information',
    closing: 'Sincerely yours,',
    defaultSubject: 'Motorcycle Payment Invoice',
    defaultFooterInfo: 'Please make payment to :\nName : PT. WAJIRA JAGRATARA MORINDO\nBCA Account Number : 456-581-1313\nNPWP : 65.546.691.0-542.000',
    cancel: 'Cancel',
    save: 'Save',
    saving: 'Saving...',
    fallbackSubject: 'DOCUMENT TEMPLATE',
    paymentPlaceholder: 'Payment information',
  }
};

interface Props {
  initialData?: DocumentTemplate;
  isSubmitting?: boolean;
  onSubmit: (values: DocumentTemplateFormValues) => void;
  onCancel: () => void;
}

function EditorToolbar({ editor }: { editor: Editor | null }) {
  return (
    <div className="flex gap-1 rounded-md border bg-white p-2">
      <button type="button" aria-label="Tebal" onClick={() => editor?.chain().focus().toggleBold().run()}><Bold className="h-4 w-4" /></button>
      <button type="button" aria-label="Miring" onClick={() => editor?.chain().focus().toggleItalic().run()}><Italic className="h-4 w-4" /></button>
      <button type="button" aria-label="Bullet list" onClick={() => editor?.chain().focus().toggleBulletList().run()}><List className="h-4 w-4" /></button>
      <button type="button" aria-label="Numbered list" onClick={() => editor?.chain().focus().toggleOrderedList().run()}><ListOrdered className="h-4 w-4" /></button>
      <button type="button" aria-label="Undo" onClick={() => editor?.chain().focus().undo().run()}><Undo2 className="h-4 w-4" /></button>
      <button type="button" aria-label="Redo" onClick={() => editor?.chain().focus().redo().run()}><Redo2 className="h-4 w-4" /></button>
    </div>
  );
}

export function DocumentTemplateEditor({ initialData, isSubmitting, onSubmit, onCancel }: Props) {
  const [documentPreview, setDocumentPreview] = useState<string | null>(initialData?.documentTemplate ?? null);
  const [signaturePreview, setSignaturePreview] = useState<string | null>(initialData?.personSignature ?? null);

  const langInit = initialData?.language === 'en' ? 'en' : 'id';
  const defaultSubject = initialData?.subject ?? translations[langInit].defaultSubject;
  const defaultHeader = initialData?.headerInformation || `<p>${translations[langInit].intro}</p>`;
  const defaultFooter = initialData?.footerInformation ?? translations[langInit].defaultFooterInfo;
  const defaultTableColor = initialData?.tableColor || '#1f4163';

  const { register, handleSubmit, setValue, watch, formState: { errors } } = useForm<DocumentTemplateFormValues>({
    resolver: zodResolver(documentTemplateSchema),
    defaultValues: {
      name: initialData?.name ?? '',
      language: langInit,
      subject: defaultSubject,
      headerInformation: defaultHeader,
      footerInformation: defaultFooter,
      tableColor: defaultTableColor,
      personSignature: null,
      personSigner: initialData?.personSigner ?? 'Zaifudin Yukhri',
      documentTemplate: null
    },
  });

  const subject = watch('subject');
  const tableColor = watch('tableColor');
  const personSigner = watch('personSigner');
  const language = watch('language');

  const currentLang = (language === 'en' ? 'en' : 'id') as 'id' | 'en';
  const t = translations[currentLang];

  const headerEditor = useEditor({
    extensions: [StarterKit],
    content: defaultHeader,
    immediatelyRender: false,
    onUpdate: ({ editor: next }) => setValue('headerInformation', next.getHTML(), { shouldDirty: true, shouldValidate: true })
  });

  useEffect(() => {
    if (headerEditor && initialData?.headerInformation) {
      headerEditor.commands.setContent(initialData.headerInformation);
    }
  }, [headerEditor, initialData?.headerInformation]);

  const footerEditor = useEditor({
    extensions: [StarterKit],
    content: defaultFooter,
    immediatelyRender: false,
    onUpdate: ({ editor: next }) => setValue('footerInformation', next.getHTML(), { shouldDirty: true, shouldValidate: true })
  });

  useEffect(() => {
    if (footerEditor && initialData?.footerInformation) {
      footerEditor.commands.setContent(initialData.footerInformation);
    }
  }, [footerEditor, initialData?.footerInformation]);

  const prevLanguageRef = useRef(language);

  useEffect(() => {
    const prevLang = prevLanguageRef.current;
    if (prevLang && prevLang !== language) {
      const currentSubject = watch('subject');
      const currentHeader = watch('headerInformation');
      const currentFooter = watch('footerInformation');

      const oldDefaults = translations[prevLang as 'id' | 'en'];
      const newDefaults = translations[language as 'id' | 'en'];

      if (currentSubject === oldDefaults.defaultSubject || !currentSubject) {
        setValue('subject', newDefaults.defaultSubject, { shouldValidate: true });
      }

      const normalizedHeader = currentHeader ? currentHeader.replace(/<[^>]*>/g, '').trim() : '';
      const normalizedOldHeader = oldDefaults.intro.trim();
      if (normalizedHeader === normalizedOldHeader || !currentHeader) {
        const newHeader = `<p>${newDefaults.intro}</p>`;
        setValue('headerInformation', newHeader, { shouldValidate: true });
        headerEditor?.commands.setContent(newHeader);
      }

      const normalizedCurrent = currentFooter ? currentFooter.replace(/<[^>]*>/g, '').trim() : '';
      const normalizedOldDefault = oldDefaults.defaultFooterInfo.replace(/<[^>]*>/g, '').trim().replace(/\n/g, ' ');

      if (
        normalizedCurrent === normalizedOldDefault ||
        normalizedCurrent === oldDefaults.defaultFooterInfo.trim() ||
        !currentFooter
      ) {
        setValue('footerInformation', newDefaults.defaultFooterInfo, { shouldValidate: true });
        footerEditor?.commands.setContent(newDefaults.defaultFooterInfo);
      }
    }
    prevLanguageRef.current = language;
  }, [language, setValue, headerEditor, footerEditor, watch]);

  const fileUrl = (file: File | null, setPreview: (url: string | null) => void) => {
    if (!file) {
      setPreview(null);
      return;
    }

    const reader = new FileReader();

    reader.onload = () => {
      setPreview(typeof reader.result === 'string' ? reader.result : null);
    };

    reader.onerror = () => {
      setPreview(null);
    };

    reader.readAsDataURL(file);
  };

  const submit = (values: DocumentTemplateFormValues) => onSubmit(values);

  return (
    <form onSubmit={handleSubmit(submit)} className="space-y-6">
      <div className="grid gap-6 xl:grid-cols-[360px_minmax(0,1fr)]">
        <div className="space-y-4 rounded-md border bg-white p-5 shadow-sm">
          <div>
            <Label htmlFor="name">{t.nameLabel}</Label>
            <Input id="name" {...register('name')} placeholder={t.nameLabel} className="mt-1" />
            {errors.name && <p className="mt-1 text-xs text-red-600">{errors.name.message}</p>}
          </div>
          <div>
            <Label>{t.languageLabel}</Label>
            <Select value={language} onValueChange={(value: 'id' | 'en') => setValue('language', value, { shouldValidate: true })}>
              <SelectTrigger className="mt-1">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="id">Bahasa Indonesia</SelectItem>
                <SelectItem value="en">English</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div>
            <Label htmlFor="subject">{t.subjectFieldLabel}</Label>
            <Input id="subject" {...register('subject')} className="mt-1" />
            {errors.subject && <p className="mt-1 text-xs text-red-600">{errors.subject.message}</p>}
          </div>
          <div>
            <Label>{t.headerInformationLabel}</Label>
            <p className="mt-1 text-xs text-slate-500">{t.headerInformationHint}</p>
            {errors.headerInformation && <p className="mt-1 text-xs text-red-600">{errors.headerInformation.message}</p>}
          </div>
          <div>
            <Label htmlFor="table-color">{t.tableColorLabel}</Label>
            <div className="mt-1 flex items-center gap-2">
              <input id="table-color" type="color" {...register('tableColor')} className="h-10 w-14 cursor-pointer rounded border border-slate-200 bg-white p-1" />
              <Input value={tableColor} onChange={(event) => setValue('tableColor', event.target.value, { shouldDirty: true, shouldValidate: true })} className="font-mono uppercase" />
            </div>
            {errors.tableColor && <p className="mt-1 text-xs text-red-600">{errors.tableColor.message}</p>}
          </div>
          <div>
            <Label htmlFor="person-signature">{t.signatureLabel}</Label>
            <FileInput id="person-signature" accept="image/png,image/jpeg" value={watch('personSignature')} onFileChange={(file) => { setValue('personSignature', file, { shouldValidate: true }); fileUrl(file, setSignaturePreview); }} className="mt-1" />
            <p className="mt-1 text-xs text-slate-500">{t.signatureHint}</p>
          </div>
          <div>
            <Label htmlFor="personSigner">{t.signerLabel}</Label>
            <Input id="personSigner" {...register('personSigner')} className="mt-1" />
            {errors.personSigner && <p className="mt-1 text-xs text-red-600">{errors.personSigner.message}</p>}
          </div>
          <div>
            <Label>{t.documentLabel}</Label>
            <FileInput id="document-template" accept="image/png,image/jpeg" value={watch('documentTemplate')} onFileChange={(file) => { setValue('documentTemplate', file, { shouldValidate: true }); fileUrl(file, setDocumentPreview); }} className="mt-1" />
            <p className="mt-1 text-xs text-slate-500">Upload satu gambar desain dokumen penuh. Konten sistem akan dirender di atas template ini.</p>
          </div>
          <div className="flex gap-2 pt-2">
            <Button type="button" variant="outline" onClick={onCancel} className="flex-1">{t.cancel}</Button>
            <Button type="submit" disabled={isSubmitting} className="flex-1 bg-[#1e3a5f]">
              {isSubmitting ? t.saving : t.save}
            </Button>
          </div>
        </div>

        <div className="space-y-3 overflow-auto rounded-md bg-slate-100 p-4">
          <EditorToolbar editor={headerEditor} />
          <div className="mx-auto min-h-[1123px] w-[794px] overflow-hidden bg-white shadow-md" style={{ backgroundImage: documentPreview ? `url(${getObjectStorageUrl(documentPreview)})` : undefined, backgroundSize: '100% 100%', backgroundPosition: 'center', backgroundRepeat: 'no-repeat' }}>
            <div className="flex min-h-[1123px] flex-col px-[76px] pb-[76px] pt-[160px]">
              <div className="flex-1">
                <div className="flex justify-between text-sm">
                  <div>
                    <p>{t.invoiceNumber}: <strong>INV/2026/0001</strong></p>
                    <p>{t.subjectLabel}: {subject || '-'}</p>
                    <p>{t.toLabel}: Customer Dummy</p>
                    <p>{language === 'en' ? 'Sheet' : 'Lembar'}: <strong>1</strong></p>
                  </div>
                  <p>{t.dateLabel}</p>
                </div>
                <h1 className="mt-8 text-center text-xl font-bold tracking-widest underline">{subject || t.fallbackSubject}</h1>
                <p className="mt-6 text-sm">{t.salutation}</p>
                <EditorContent editor={headerEditor} className="mt-1 text-sm prose prose-sm max-w-none" dangerouslySetInnerHTML={undefined} />

                <table className="mt-5 w-full border-collapse text-xs">
                  <thead>
                    <tr style={{ backgroundColor: tableColor }} className="text-white">
                      {t.tableHeaders.map((head) => <th key={head} className="border border-white/20 px-2 py-2">{head}</th>)}
                    </tr>
                  </thead>
                  <tbody>
                    {dummyRows.map((row) => (
                      <tr key={row[0]}>
                        {row.map((cell) => <td key={cell} className="border border-slate-200 px-2 py-2">{cell}</td>)}
                      </tr>
                    ))}
                    <tr className="font-semibold">
                      <td colSpan={5} className="border border-slate-200 px-2 py-2 text-right">{t.total}</td>
                      <td className="border border-slate-200 px-2 py-2">Rp 60.500.000</td>
                    </tr>
                  </tbody>
                </table>

                <div className="mt-8 rounded border border-slate-200 p-3 text-sm">
                  <div className="mb-2 font-semibold">{t.paymentInfo}</div>
                  <EditorContent editor={footerEditor} className="prose prose-sm max-w-none" dangerouslySetInnerHTML={undefined} />
                </div>
              </div>

              <div className="mb-38 text-end text-sm">
                <p className='mr-12'>{t.closing}</p>
                <div className="flex mr-[12.3px] items-center justify-end">
                  <StorageImage src={signaturePreview} alt="Tanda tangan" width={160} height={85} className="max-h-24 max-w-40 object-contain" />
                </div>
                <p className="mr-12 font-semibold underline">{personSigner || '-'}</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </form>
  );
}
