import { z } from 'zod';

export const unitTransactionSchema = z.object({
  unitTypeId: z.string().min(1, 'Tipe Unit wajib dipilih'),
  documentTemplateId: z.union([z.string(), z.number()]).nullable().optional(),
  qty: z.number().min(1, 'QTY minimal 1'),
  price: z.number().min(0, 'Harga tidak boleh negatif'),
  bbnPrice: z.number().min(0).optional(),
  expeditionFee: z.number().min(0).optional(),
  otherFee: z.number().min(0).optional(),
  priceUsd: z.number().min(0).optional(),
  pricePerUnitUsd: z.number().min(0).optional(),
  dppTaxVersionId: z.union([z.string(), z.number()]).optional(),
  ppnTaxVersionId: z.union([z.string(), z.number()]).optional(),
  hppPerUnit: z.number().min(0).optional(),
  dppPerUnit: z.number().min(0).optional(),
  ppnPerUnit: z.number().min(0).optional(),
  hppTotal: z.number().min(0).optional(),
  dppTotal: z.number().min(0).optional(),
  ppnTotal: z.number().min(0).optional(),
  usdCostsFreight: z.number().min(0).optional(),
  usdCostsBoxPacking: z.number().min(0).optional(),
  usdCostsAdminCost: z.number().min(0).optional(),
  usdCostsCkdProcessingCost: z.number().min(0).optional(),
  usdCostsBillOfLadingSwitchCost: z.number().min(0).optional(),
  usdCostsCustomsClearanceCost: z.number().min(0).optional(),
  usdCostsOther: z.array(z.object({
    id: z.number().optional(),
    note: z.string().nullable().optional(),
    amount: z.number().min(0),
  })).optional(),
  usd_costs: z.array(z.object({
    id: z.number().optional(),
    cost_type: z.string(),
    amount: z.number().min(0),
    note: z.string().nullable().optional(),
  })).optional(),
});
